const std = @import("std");
const typecast = @import("typecast");

pub fn main() !void {
    var gpa = std.heap.GeneralPurposeAllocator(.{}){};
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    // Read API key from environment
    const api_key = std.posix.getenv("TYPECAST_API_KEY") orelse {
        std.debug.print("Error: TYPECAST_API_KEY environment variable not set.\n", .{});
        std.process.exit(1);
    };

    const base_url = std.posix.getenv("TYPECAST_API_HOST") orelse "https://api.typecast.ai";

    // Create client
    var client = typecast.Client.init(allocator, .{
        .api_key = api_key,
        .base_url = base_url,
    });
    defer client.deinit();

    // Synthesize speech
    std.debug.print("Synthesizing speech...\n", .{});

    const response = try client.textToSpeech(.{
        .voice_id = "tc_672c5f5ce59fac2a48faeaee",
        .text = "Hello! This audio was generated by the Typecast Zig SDK.",
        .model = .ssfm_v30,
    });
    defer allocator.free(response.audio_data);

    // Write audio to file
    const path = "output.wav";
    const file = try std.fs.cwd().createFile(path, .{});
    defer file.close();
    try file.writeAll(response.audio_data);

    std.debug.print("Saved {s} ({d} bytes, {d:.2}s)\n", .{
        path,
        response.audio_data.len,
        response.duration,
    });
}
